version: "3.7"
services:
  backend:
    image: ${DOCKER_IMAGES_PREFIX}/backend:${DJANGO_REACT_TEMPLATE_VERSION}
    restart: unless-stopped
    build: backend/
    environment:
      - DJANGO_SETTINGS_MODULE
      - DJANGO_REACT_TEMPLATE_DB_URL=mongodb://database:27017
      - DJANGO_REACT_TEMPLATE_SECRET_KEY
      - RECAPTCHA_SERVER_KEY
    volumes:
      - backend_static_files:/app/static/
    ports:
      - "80"
    depends_on:
      - database
  database:
    image: mongo:5.0.9-focal
    restart: unless-stopped
    ports:
      - $DB_PORT_MAPPING
    volumes:
      - ./.db-data/:/data/db/
  frontend:
    build: ./frontend
    image: ${DOCKER_IMAGES_PREFIX}/frontend:${DJANGO_REACT_TEMPLATE_VERSION}
    environment:
      - API_BASE_URL
    volumes:
      - frontend_files:/mnt/frontend/
  nginx:
    image: nginx:1.23.0-alpine
    ports:
      - "443:443"
      - "80:80"
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - $FULLCHAIN_PATH:/etc/ssl-files/fullchain.pem:ro
      - $PRIVKEY_PATH:/etc/ssl-files/privkey.pem:ro
      - backend_static_files:/app/static/:ro
      - frontend_files:/mnt/frontend/:ro
    depends_on:
      - backend
      - frontend

volumes:
  backend_static_files:
  frontend_files:
