version: "3.7"
services:
  backend:
    build: backend/
    environment:
      - PARCHIN_DB_URL=mongodb://database:27017
      - PARCHIN_SECRET_KEY
    ports:
      - 8080:80
    depends_on:
      - database
  database:
    image: mongo:5.0.9-focal
    ports:
      - 27017
    volumes:
      - ./.db-data/:/data/db/
