version: "3.7"
services:
  backend:
    image: ${DOCKER_IMAGES_PREFIX}/backend:${PARCHIN_VERSION}
    build: backend/
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings-production
      - PARCHIN_DB_URL=mongodb://database:27017
      - PARCHIN_SECRET_KEY
      - RECAPTCHA_SERVER_KEY
    ports:
      - 8080:80
    depends_on:
      - database
  database:
    image: mongo:5.0.9-focal
    ports:
      - $DB_PORT_MAPPING
    volumes:
      - ./.db-data/:/data/db/
